name: Proxy smoke (Vercel preview)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  proxy-check:
    runs-on: ubuntu-latest
    env:
      TEST_BASE: ${{ secrets.VERCEL_PREVIEW_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (frontend only)
        working-directory: gaish-elmafdein-nextjs
        run: npm ci

      - name: Run proxy smoke tests
        run: |
          node --version
          npm --version
          node scripts/test-proxy.mjs
