name: Proxy smoke (preview + prod)

on:
  workflow_dispatch:
    inputs:
      test_base:
        description: "Override base URL for preview run"
        required: false
        default: ""
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  determine:
    runs-on: ubuntu-latest
    outputs:
      preview_should_run: ${{ steps.set.outputs.preview_should_run }}
      prod_should_run: ${{ steps.set.outputs.prod_should_run }}
      preview_base: ${{ steps.set.outputs.preview_base }}
      prod_base: ${{ steps.set.outputs.prod_base }}
    steps:
      - name: Compute flags
        id: set
        run: |
          PREVIEW_INPUT="${{ github.event.inputs.test_base }}"
          PREVIEW_SECRET="${{ secrets.VERCEL_PREVIEW_URL }}"
          PROD_SECRET="${{ secrets.PROD_URL }}"

          # preview base
          if [ -n "$PREVIEW_INPUT" ]; then
            echo "preview_base=$PREVIEW_INPUT" >> $GITHUB_OUTPUT
            echo "preview_should_run=true" >> $GITHUB_OUTPUT
          elif [ -n "$PREVIEW_SECRET" ]; then
            echo "preview_base=$PREVIEW_SECRET" >> $GITHUB_OUTPUT
            echo "preview_should_run=true" >> $GITHUB_OUTPUT
          else
            echo "preview_base=" >> $GITHUB_OUTPUT
            echo "preview_should_run=false" >> $GITHUB_OUTPUT
          fi

          # prod base
            if [ -n "$PROD_SECRET" ]; then
              echo "prod_base=$PROD_SECRET" >> $GITHUB_OUTPUT
              echo "prod_should_run=true" >> $GITHUB_OUTPUT
            else
              echo "prod_base=" >> $GITHUB_OUTPUT
              echo "prod_should_run=false" >> $GITHUB_OUTPUT
            fi

  preview:
    needs: determine
    if: needs.determine.outputs.preview_should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Warmup
        env:
          TEST_BASE: ${{ needs.determine.outputs.preview_base }}
        run: |
          echo "TEST_BASE=$TEST_BASE"
          curl -sS "$TEST_BASE/api/health" || exit 1

      - name: Run smoke tests (preview)
        env:
          TEST_BASE: ${{ needs.determine.outputs.preview_base }}
        run: |
          node scripts/test-proxy.mjs

  prod:
    needs: determine
    if: needs.determine.outputs.prod_should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Warmup
        env:
          TEST_BASE: ${{ needs.determine.outputs.prod_base }}
        run: |
          echo "TEST_BASE=$TEST_BASE"
          curl -sS "$TEST_BASE/api/health" || exit 1

      - name: Run smoke tests (prod)
        env:
          TEST_BASE: ${{ needs.determine.outputs.prod_base }}
        run: |
          node scripts/test-proxy.mjs
