name: Proxy smoke (preview + prod)

on:
  workflow_dispatch:
    inputs:
      test_base:
        description: 'Base URL to test (optional)'
        required: false
        default: ''
  push:
    branches: [ main ]   # يشغّل فحص الإنتاج تلقائيًا بعد الدفع

concurrency:
  group: proxy-smoke-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  preview:
    name: Preview
    # Run if: (manual dispatch with non-empty input) OR (push with secret available)
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.test_base != '') || (github.event_name == 'push' && secrets.VERCEL_PREVIEW_URL != '') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TEST_BASE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_base || secrets.VERCEL_PREVIEW_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Warmup target
        run: |
          if [ -z "${TEST_BASE}" ]; then echo "TEST_BASE empty; nothing to test"; exit 1; fi
          echo "Warming ${TEST_BASE}/api/health"
          curl -sS -m 20 -f "${TEST_BASE}/api/health" || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: gaish-elmafdein-nextjs
        run: npm ci

      - name: Run proxy smoke (preview)
        working-directory: gaish-elmafdein-nextjs
        env:
          TEST_BASE: ${{ env.TEST_BASE }}
        run: |
          echo "Testing against $TEST_BASE"
          node ../scripts/test-proxy.mjs || (echo "Retry after 5s..." && sleep 5 && node ../scripts/test-proxy.mjs)

  prod:
    name: Production
    if: ${{ secrets.PROD_URL != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TEST_BASE: ${{ secrets.PROD_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Warmup target
        run: |
          if [ -z "${TEST_BASE}" ]; then echo "TEST_BASE empty; nothing to test"; exit 1; fi
          echo "Warming ${TEST_BASE}/api/health"
          curl -sS -m 20 -f "${TEST_BASE}/api/health" || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: gaish-elmafdein-nextjs
        run: npm ci

      - name: Run proxy smoke (prod)
        working-directory: gaish-elmafdein-nextjs
        env:
          TEST_BASE: ${{ env.TEST_BASE }}
        run: |
          echo "Testing against $TEST_BASE"
          node ../scripts/test-proxy.mjs || (echo "Retry after 5s..." && sleep 5 && node ../scripts/test-proxy.mjs)
