name: Proxy smoke (preview + prod)

on:
  workflow_dispatch:
    inputs:
      test_base:
        description: "Override base URL (optional)"
        required: false
        type: string
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  determine:
    runs-on: ubuntu-latest
    outputs:
      preview_should_run: ${{ steps.flags.outputs.preview_should_run }}
      prod_should_run:    ${{ steps.flags.outputs.prod_should_run }}
    steps:
      - id: flags
        shell: bash
        run: |
          has_input="${{ inputs.test_base != '' }}"
          has_preview="${{ secrets.VERCEL_PREVIEW_URL != '' }}"
          has_prod="${{ secrets.PROD_URL != '' }}"

          if [[ "$has_input" == "true" || "$has_preview" == "true" ]]; then
            echo "preview_should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "preview_should_run=false" >> "$GITHUB_OUTPUT"
          fi

          if [[ "$has_prod" == "true" ]]; then
            echo "prod_should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "prod_should_run=false" >> "$GITHUB_OUTPUT"
          fi

  preview:
    needs: determine
    if: needs.determine.outputs.preview_should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set TEST_BASE (preview or input)
        shell: bash
        run: |
          if [[ -n "${{ inputs.test_base }}" ]]; then
            echo "TEST_BASE=${{ inputs.test_base }}" >> "$GITHUB_ENV"
          else
            echo "TEST_BASE=${{ secrets.VERCEL_PREVIEW_URL }}" >> "$GITHUB_ENV"
          fi
          echo "Using TEST_BASE=$TEST_BASE"

      - name: Install deps (frontend only)
        run: npm --prefix gaish-elmafdein-nextjs ci

      - name: Warmup (non-blocking)
        continue-on-error: true
        run: node scripts/test-proxy.mjs --only health

      - name: Proxy smoke - preview
        run: npm --prefix gaish-elmafdein-nextjs run test:proxy

  prod:
    needs: determine
    if: needs.determine.outputs.prod_should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set TEST_BASE (prod)
        shell: bash
        run: |
          echo "TEST_BASE=${{ secrets.PROD_URL }}" >> "$GITHUB_ENV"
          echo "Using TEST_BASE=$TEST_BASE"

      - name: Install deps (frontend only)
        run: npm --prefix gaish-elmafdein-nextjs ci

      - name: Warmup (non-blocking)
        continue-on-error: true
        run: node scripts/test-proxy.mjs --only health

      - name: Proxy smoke - prod
        run: npm --prefix gaish-elmafdein-nextjs run test:proxy
