name: Proxy smoke (preview + prod)

on:
  workflow_dispatch:
    inputs:
      test_base:
        description: 'Base URL to test (optional)'
        required: false
        default: ''
  push:
    branches: [ main ]   # يشغّل فحص الإنتاج تلقائيًا بعد الدفع

concurrency:
  group: proxy-smoke-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  preview:
    name: Preview (input or secret)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TEST_BASE: ${{ github.event.inputs.test_base != '' && github.event.inputs.test_base || secrets.VERCEL_PREVIEW_URL }}
    steps:
      - name: Validate TEST_BASE
        run: |
          if [ -z "${TEST_BASE}" ]; then
            echo "TEST_BASE is empty (provide input or set VERCEL_PREVIEW_URL secret)"; exit 1;
          fi
          if ! echo "$TEST_BASE" | grep -Eq "^https?://"; then
            echo "Invalid TEST_BASE (must start with http/https)"; exit 1;
          fi
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        working-directory: gaish-elmafdein-nextjs
        run: npm ci
      - name: Warmup
        run: |
          set -e
          for p in "/" "/api/health" "/ar/library"; do
            echo "→ GET $TEST_BASE$p"
            curl -sS -m 20 -f "$TEST_BASE$p" >/dev/null || true
          done
      - name: Run proxy smoke
        working-directory: gaish-elmafdein-nextjs
        env:
          TEST_BASE: ${{ env.TEST_BASE }}
        run: |
          node ../scripts/test-proxy.mjs || (echo "first try failed; retrying…" && sleep 5 && node ../scripts/test-proxy.mjs)

  prod:
    name: Production (PROD_URL secret)
    needs: [ preview ]
    if: ${{ secrets.PROD_URL != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TEST_BASE: ${{ secrets.PROD_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        working-directory: gaish-elmafdein-nextjs
        run: npm ci
      - name: Warmup
        run: |
          for p in "/" "/api/health" "/ar/library"; do
            echo "→ GET $TEST_BASE$p"
            curl -sS -m 20 -f "$TEST_BASE$p" >/dev/null || true
          done
      - name: Run proxy smoke (prod)
        working-directory: gaish-elmafdein-nextjs
        env:
          TEST_BASE: ${{ env.TEST_BASE }}
        run: |
          node ../scripts/test-proxy.mjs || (echo "first try failed; retrying…" && sleep 5 && node ../scripts/test-proxy.mjs)
